/**
 * useAISearch — searches for recipes by calling the ai-search-recipes Edge Function.
 *
 * Recipes are generated by OpenAI and saved to the DB immediately.
 * Results include recipe_id so cards can navigate directly without a separate import step.
 *
 * Module-level cache keeps results for 10 minutes so repeated searches are instant.
 */
import { useState, useCallback, useRef } from 'react';
import { supabase } from '@/lib/supabase';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AIRecipeCard = {
  recipe_id: string;
  title: string;
  description: string | null;
  emoji: string;
  cuisine: string | null;
  difficulty: string;
  total_time_min: number | null;
  calories_per_serving: number | null;
  protein_per_serving: number | null;
  fat_per_serving: number | null;
  carbs_per_serving: number | null;
  fibre_per_serving: number | null;
  meal_types: string[];
  diet_types: string[];
};

export type AISearchParams = {
  query: string;
  mealType?: string;
  count?: number;
};

// ---------------------------------------------------------------------------
// Module-level cache (survives re-renders, resets on app restart)
// ---------------------------------------------------------------------------

type CacheEntry = {
  results: AIRecipeCard[];
  timestamp: number;
};

const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes
const searchCache = new Map<string, CacheEntry>();

function getCacheKey(params: AISearchParams): string {
  return `${params.query.trim().toLowerCase()}::${params.mealType ?? ''}`;
}

function getCached(key: string): AIRecipeCard[] | null {
  const entry = searchCache.get(key);
  if (!entry) return null;
  if (Date.now() - entry.timestamp > CACHE_TTL_MS) {
    searchCache.delete(key);
    return null;
  }
  return entry.results;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useAISearch() {
  const [results, setResults] = useState<AIRecipeCard[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const activeQueryRef = useRef<string | null>(null);

  const search = useCallback(async (params: AISearchParams) => {
    const trimmedQuery = params.query.trim();
    if (!trimmedQuery || trimmedQuery.length < 2) {
      setResults([]);
      setError(null);
      return;
    }

    const cacheKey = getCacheKey(params);

    // Serve from cache instantly — no loading state shown
    const cached = getCached(cacheKey);
    if (cached) {
      setResults(cached);
      setError(null);
      return;
    }

    // Track current query to ignore stale responses
    activeQueryRef.current = cacheKey;
    setLoading(true);
    setError(null);

    try {
      const { data, error: fnError } = await supabase.functions.invoke('ai-search-recipes', {
        body: {
          query: trimmedQuery,
          count: params.count ?? 8,
          mealType: params.mealType,
        },
      });

      // Ignore stale responses if a newer search was started
      if (activeQueryRef.current !== cacheKey) return;

      if (fnError) throw new Error(fnError.message || 'Search failed');
      if (data?.error) throw new Error(data.error);

      const recipes: AIRecipeCard[] = data?.recipes ?? [];

      // Store in cache
      searchCache.set(cacheKey, { results: recipes, timestamp: Date.now() });

      setResults(recipes);
    } catch (err: any) {
      if (activeQueryRef.current !== cacheKey) return;
      setError(err.message || 'Could not generate recipes. Please try again.');
      setResults([]);
    } finally {
      if (activeQueryRef.current === cacheKey) {
        setLoading(false);
      }
    }
  }, []);

  const clearResults = useCallback(() => {
    setResults([]);
    setError(null);
    activeQueryRef.current = null;
  }, []);

  return { results, loading, error, search, clearResults };
}
